# VELES DRIVE - Упрощенная конфигурация для легкого деплоя
version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: veles_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init.js:ro
    networks:
      - veles_net
    command: --auth

  # Backend API
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.simple
      target: backend
    container_name: veles_backend
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongodb:27017/${DB_NAME}?authSource=admin
      - DB_NAME=${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGINS=${CORS_ORIGINS}
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    networks:
      - veles_net
    volumes:
      - uploads_data:/app/uploads

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.simple
      target: frontend
      args:
        - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
    container_name: veles_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - veles_net

volumes:
  mongo_data:
  uploads_data:

networks:
  veles_net:
    driver: bridge